# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [3]:
import numpy as np
from random import randint

In [4]:
# Your code here
A = np.zeros([3,3])

for i in A:
    for ind,val in enumerate(i):
        i[ind] = randint(0,9)

B = np.zeros([3,3])

for i in B:
    for ind,val in enumerate(i):
        i[ind] = randint(0,9)

C = np.zeros([3,3])

for i in C:
    for ind,val in enumerate(i):
        i[ind] = randint(0,9)


np.dot(A,(B+C)) == (np.dot(A,B)+np.dot(A,C))


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [5]:
# Your code here 
np.dot(A, np.dot(B,C)) == np.dot(np.dot(A,B), C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [6]:
# Your code here 
np.dot(A,B) != np.dot(B,A)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [11]:
# Your code here 
np.dot(A.T, B) == np.dot(B.T, A)


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = A^T \cdot B^T $

In [8]:
# Your code here 
np.dot(A,B).T == np.dot(B.T, A.T)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 